name: Run Cypress Tests
on: [pull_request]
jobs:
  chrome_e2e:
    runs-on: ubuntu-latest
    name: E2E on Chrome
    steps:
      - uses: actions/checkout@v2
      - uses: cypress-io/github-action@v4
        with:
          browser: chrome
  firefox_e2e:
    runs-on: ubuntu-latest
    name: E2E on Firefox
    steps:
      - uses: actions/checkout@v2
      - uses: cypress-io/github-action@v4
        with:
          browser: firefox
  edge_e2e:
    runs-on: windows-latest
    name: E2E on Edge
    steps:
      - uses: actions/checkout@v2
      - uses: cypress-io/github-action@v4
        with:
          browser: edge
